###
POST http://localhost:8067/auth/login
Content-Type: application/json

{
  "email": "testing@gmail.com",
  "password": "testing123@"
}

###
POST http://localhost:8067/auth/register
Content-Type: application/json

{
  "name": "Gustavo Daniel",
  "email": "testing@gmail.com",
  "password": "testing123@"
}